### ISSUE TITLE
For time zone 0 or U.K. md-calender shows the date 25 twice (picture attached)

### ISSUE THREAD

**Issue by ahmadalibaloch** [bradberger/angular-material-calendar#20]
Change your timezone to UK date time and check the calendar view it shows date 25 twice as shown in the picture attached.
![timezone problem](https://cloud.githubusercontent.com/assets/1916642/10417357/f85c1b0a-7051-11e5-9241-e670d33ce02b.png)

**Comment by bradberger** [comment]
Thanks for reporting that, can you confirm you're still seeing the same issue since the last update? The main heading on the website should show `v0.2.9` now. Not sure which version is loaded in the screenshot. I tried setting the timezone on my machine here, and it's working correctly, but there were issues with it a few days ago that have since been corrected.

**Comment by ahmadalibaloch** [comment]
Thanks for the reply. Its solved now. :+1:

**Comment by bradberger** [comment]
Awesome, glad to hear it! The way dates were generated was significantly improved, and unit tests added so it should be more stable from here on out.
